import type {
  EventItem,
  VideoItem,
  PostItem,
  PhotoItem,
  Photocard,
  AudioItem,
  Character,
  PlatformResType,
  AritistResType,
} from "./types";
// ==================== 日程事件 ====================
export const initialEvents: EventItem[] = [
  {
    id: "e1",
    status: "ongoing",
    title: "品牌线下活动 - 上海 IFC",
    location: "Shanghai, China",
    date: "2024.06.12",
    time: "14:00 - 18:00",
    imageUrl: "/pages/assets/images/1 (41).jpg",
    icon: "map-pin",
  },
  {
    id: "e2",
    status: "completed",
    title: "光影艺术展策划会议",
    location: "StarView Studio, Building 7",
    date: "2024.06.12",
    time: "10:00 - 11:30",
    icon: "building",
  },
  {
    id: "e3",
    status: "cancelled",
    title: "外滩建筑摄影采样",
    location: "The Bund, Shanghai",
    date: "2024.06.11",
    time: "06:00 - 09:00",
    icon: "camera",
  },
  {
    id: "e4",
    status: "completed",
    title: "档案系统数据校验",
    location: "Cloud Server Node A1",
    date: "2024.06.11",
    time: "21:00 - 23:00",
    icon: "database",
  },
];

// ==================== 视频档案 ====================
export const initialVideos: VideoItem[] = [
  {
    id: "v1",
    title: "都市回响：东京极速夜",
    duration: "03:24",
    date: "JUNE 24",
    thumbnail: "/pages/assets/images/1 (5).jpg",
    tags: ["VLOG", "东京", "INSTAGRAM"],
    description:
      "通过变形镜头探索新宿霓虹闪烁的走廊。对午夜后光影与城市节奏的研究。",
    publishedTime: "03:24",
    platform: "4K HDR",
  },
  {
    id: "v2",
    title: "CHASSIS_STRESS_TEST_V04",
    duration: "04:22",
    date: "JUNE 08",
    thumbnail: "/pages/assets/images/1 (6).jpg",
    tags: ["Technicals", "Cinematics"],
    description: "电影级广角拍摄未来主义汽车设计工作室，深色高对比度灯光。",
    publishedTime: "14:00",
    platform: "ARCHIVE",
  },
  {
    id: "v3",
    title: "ENGINE_CALIBRATION_RESONANCE",
    duration: "12:10",
    date: "JUNE 08",
    thumbnail: "/pages/assets/images/1 (7).jpg",
    tags: ["Cinematics", "Technicals"],
    description: "高性能引擎部件的技术特写，在漆黑工业环境中被聚光灯照亮。",
    publishedTime: "15:15",
    platform: "4K",
  },
  {
    id: "v4",
    title: "DASHBOARD_STILLNESS_LUMINESCENCE",
    duration: "01:45",
    date: "JUNE 05",
    thumbnail: "/pages/assets/images/1 (8).jpg",
    tags: ["Cinematics", "Interviews"],
    description: "豪华跑车仪表盘的暗调电影级视图，极简数字显示屏映衬纯黑内饰。",
    publishedTime: "10:00",
    platform: "RAW",
  },
  {
    id: "v5",
    title: "BRUTAL_ASYMMETRY_HAIRLINES",
    duration: "08:55",
    date: "JUNE 05",
    thumbnail: "/pages/assets/images/1 (9).jpg",
    tags: ["Archive Logs"],
    description: "工业档案馆中锐利竖线与阴影的抽象建筑构图，现代粗野主义风格。",
    publishedTime: "11:00",
    platform: "LOG",
  },
  {
    id: "v6",
    title: "ROBOTIC_LASER_INTEGRATION",
    duration: "03:00",
    date: "MAY 22",
    thumbnail: "/pages/assets/images/1 (10).jpg",
    tags: ["Technicals"],
    description: "黑暗工厂中激光引导的精密机器人装配线，高对比度黑色工业美学。",
    publishedTime: "18:30",
    platform: "UHD",
  },
  {
    id: "v7",
    title: "CINEMATIC_ARCHIVE_DATA_MATRIX",
    duration: "22:15",
    date: "MAY 22",
    thumbnail: "/pages/assets/images/1 (11).jpg",
    tags: ["Archive Logs", "Technicals"],
    description: "展示复杂数据网格和档案信息的暗色数字界面，极简电影数据中心。",
    publishedTime: "19:45",
    platform: "MATRIX-RAW",
  },
];

// ==================== 社交动态 ====================
export const initialPosts: PostItem[] = [
  {
    id: "p1",
    title: "城市漫游系列：午夜的上海街道，光影在钢筋水泥间流淌的瞬间。",
    date: "2023.10.24",
    publishedTime: "12:45 PUBLISHED",
    platform: "WEIBO",
    images: [
      "/pages/assets/images/1 (12).jpg",
      "/pages/assets/images/1 (13).jpg",
      "/pages/assets/images/1 (14).jpg",
    ],
    icon: "share",
  },
  {
    id: "p2",
    title: "Minimalist architecture in Berlin. Cold materials and sharp lines.",
    date: "2023.10.23",
    publishedTime: "09:15 PUBLISHED",
    platform: "INSTAGRAM",
    images: ["/pages/assets/images/1 (15).jpg"],
    icon: "camera_alt",
  },
  {
    id: "p3",
    title: "影调与情绪：关于暗调摄影的后期逻辑分享。",
    date: "2023.10.22",
    publishedTime: "22:30 PUBLISHED",
    platform: "XIAOHONGSHU",
    images: [
      "/pages/assets/images/1 (16).jpg",
      "/pages/assets/images/1 (17).jpg",
    ],
    icon: "video_library",
  },
];

// ==================== 照片档案 ====================
export const initialPhotos: PhotoItem[] = [
  {
    id: "ph1",
    url: "/pages/assets/images/1 (18).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Brutalist concrete space dawning",
    file_name: "IMG_2026_0608_01.RAW",
    location: "Tokyo dawning structural, Japan",
    tags: ["BRUTALISM", "TOKYO", "RAW"],
    type: "RAW",
    region: "Tokyo",
    system: "Phase One",
  },
  {
    id: "ph2",
    url: "/pages/assets/images/1 (19).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Vintage analog camera setup",
    file_name: "IMG_2026_0608_02.RAW",
    location: "StarView Shanghai Studio",
    tags: ["STILL_LIFE", "LEICA", "RAW"],
    type: "RAW",
    region: "Shanghai",
    system: "Leica M",
  },
  {
    id: "ph3",
    url: "/pages/assets/images/1 (20).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Misty Snow Mountains high altitude",
    file_name: "IMG_2026_0608_03.RAW",
    location: "Alps range, Europe",
    tags: ["LANDSCAPE", "SNOW", "HASSELBLAD"],
    type: "Portrait",
    region: "Berlin",
    system: "Hasselblad",
  },
  {
    id: "ph4",
    url: "/pages/assets/images/1 (21).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Brutalist staircase architecture",
    file_name: "IMG_2026_0608_04.RAW",
    location: "Berlin central station corridor",
    tags: ["ARCHITECTURE", "BRUTALISM", "RAW"],
    type: "RAW",
    region: "Berlin",
    system: "Phase One",
  },
  {
    id: "ph5",
    url: "/pages/assets/images/1 (22).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Misty dark pine forest dawning",
    file_name: "IMG_2026_0608_05.RAW",
    location: "Black Forest region, Germany",
    tags: ["LANDSCAPE", "FOREST", "RAW"],
    type: "RAW",
    region: "Berlin",
    system: "Phase One",
  },
  {
    id: "ph6",
    url: "/pages/assets/images/1 (23).jpg",
    date: "2026年06月08日",
    day: "6月8日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Macro detailed quartz crystal",
    file_name: "IMG_2026_0608_06.RAW",
    location: "NY mineral archives lab",
    tags: ["MACRO", "CRYSTAL", "STILL"],
    type: "Portrait",
    region: "New York",
    system: "Leica M",
  },
  {
    id: "ph7",
    url: "/pages/assets/images/1 (24).jpg",
    date: "2026年06月04日",
    day: "6月4日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Flow analysis motion blur study",
    file_name: "IMG_2026_0604_01.RAW",
    location: "Shinjuku highway dynamic lane",
    tags: ["ABSTRACT", "TOKYO", "MOTION"],
    type: "Video",
    region: "Tokyo",
    system: "Hasselblad",
  },
  {
    id: "ph8",
    url: "/pages/assets/images/1 (25).jpg",
    date: "2026年06月04日",
    day: "6月4日",
    month: "2026年06月",
    monthAbbr: "JUN",
    title: "Tacticle mountain granite cleft",
    file_name: "IMG_2026_0604_02.RAW",
    location: "Mt. Fuji peak ridge",
    tags: ["LANDSCAPE", "ROCK", "RAW"],
    type: "RAW",
    region: "Tokyo",
    system: "Hasselblad",
  },
  {
    id: "ph9",
    url: "/pages/assets/images/1 (26).jpg",
    date: "2026年05月20日",
    day: "5月20日",
    month: "2026年05月",
    monthAbbr: "MAY",
    title: "Dense forest canopy shafts",
    file_name: "IMG_2026_0520_01.RAW",
    location: "Shizuoka rural valley",
    tags: ["FOREST", "LIGHT_SHAFT", "RAW"],
    type: "Video",
    region: "Tokyo",
    system: "Phase One",
  },
  {
    id: "ph10",
    url: "/pages/assets/images/1 (27).jpg",
    date: "2026年05月15日",
    day: "5月15日",
    month: "2026年05月",
    monthAbbr: "MAY",
    title: "Misty sea calm horizon",
    file_name: "IMG_2026_0515_01.RAW",
    location: "Eastern coast sea lines",
    tags: ["SEA", "HORIZON", "RAW"],
    type: "Portrait",
    region: "Shanghai",
    system: "Hasselblad",
  },
];

// ==================== 小卡 ====================
export const initialCards: Photocard[] = [
  {
    id: "c1",
    title: "Crimson Echo",
    date: "24.OCT.2024",
    imageUrl: "/pages/assets/images/1 (28).jpg",
    specialEdition: true,
  },
  {
    id: "c2",
    title: "Nocturnal Shift",
    date: "12.OCT.2024",
    imageUrl: "/pages/assets/images/1 (29).jpg",
  },
  {
    id: "c3",
    title: "Stark Contrast",
    date: "05.OCT.2024",
    imageUrl: "/pages/assets/images/1 (30).jpg",
  },
  {
    id: "c4",
    title: "Void Segment",
    date: "28.SEP.2024",
    imageUrl: "/pages/assets/images/1 (31).jpg",
  },
  {
    id: "c5",
    title: "Monolith Series",
    date: "15.SEP.2024",
    imageUrl: "/pages/assets/images/1 (32).jpg",
  },
  {
    id: "c6",
    title: "Static Flow",
    date: "02.SEP.2024",
    imageUrl: "/pages/assets/images/1 (33).jpg",
  },
];

// ==================== 音频 ====================
export const initialAudio: AudioItem[] = [
  {
    id: "a1",
    title: "Atmospheric_Resonance_Site_04.wav",
    duration: "04:22",
    durationSec: 262,
    thumbnail: "/pages/assets/images/1 (34).jpg",
    author: "Hao Yiran",
    date: "2026.06.12",
    bitRate: "320kbps",
  },
  {
    id: "a2",
    title: "Deep_Field_Recording_Nocturnal.flac",
    duration: "12:45",
    durationSec: 765,
    thumbnail: "/pages/assets/images/1 (35).jpg",
    author: "Yunyi Space",
    date: "2026.06.12",
    bitRate: "LOSSLESS",
  },
  {
    id: "a3",
    title: "Urban_Static_Analysis_Log_002.mp3",
    duration: "01:15",
    durationSec: 75,
    thumbnail: "/pages/assets/images/1 (36).jpg",
    author: "Yunqi Curation",
    date: "2026.06.12",
    bitRate: "320kbps",
  },
  {
    id: "a4",
    title: "Modular_Synthesis_Drift_A.wav",
    duration: "08:30",
    durationSec: 510,
    thumbnail: "/pages/assets/images/1 (37).jpg",
    author: "StarView Lab",
    date: "2026.05.24",
    bitRate: "320kbps",
  },
];

// ==================== 轮播图 ====================
export const heroSliderImages: string[] = [
  "/pages/assets/images/1 (1).jpg",
  "/pages/assets/images/1 (2).jpg",
  "/pages/assets/images/1 (3).jpg",
  "/pages/assets/images/1 (4).jpg",
];

// ==================== 角色 ====================
export const characters: Character[] = [
  {
    id: "char1",
    artistId: "yunyi",
    name: "云熠",
    avatar: "/pages/assets/images/1 (3).jpg",
    role: "DUO HARMONY",
    accentColor: "rgb(86, 164, 173)",
  },
  {
    id: "char2",
    artistId: "haoyiran",
    name: "郝熠然",
    avatar: "/pages/assets/images/1 (46).jpg",
    role: "VOCALIST / ART DIRECTORY",
    accentColor: "#aa0a27",
  },
  {
    id: "char3",
    artistId: "yunqi",
    name: "云旗",
    avatar: "/pages/assets/images/1 (40).jpg",
    role: "PERFORMER / COMPOSER",
    accentColor: "rgb(254, 168, 53)",
  },
];
// ==================== 平台 ====================
export const systemPlantforms: PlatformResType[] = [
  {
    id: 1,
    name: "微博",
    uuid: "weibo",
    sortOrder: 1,
    createdAt: "2026-06-03T21:20:41.632Z",
    updatedAt: "2026-06-04T17:16:50.578Z",
  },
  {
    id: 2,
    name: "小红书",
    uuid: "xiaohongshu",
    sortOrder: 2,
    createdAt: "2026-06-03T21:20:48.623Z",
    updatedAt: "2026-06-04T17:16:59.947Z",
  },
  {
    id: 3,
    name: "Instagram",
    uuid: "instagram",
    sortOrder: 3,
    createdAt: "2026-06-03T21:21:06.377Z",
    updatedAt: "2026-06-04T17:17:41.891Z",
  },
  {
    id: 4,
    name: "抖音",
    uuid: "douyin",
    sortOrder: 4,
    createdAt: "2026-06-03T21:21:15.372Z",
    updatedAt: "2026-06-04T17:17:49.309Z",
  },
];
// ==================== 平台角色 ====================
export const systemArtist: AritistResType[] = [
  {
    id: 4,
    name: "云熠",
    artistId: "yunyi",
    avatar: "/uploads/1780595655393-763524.webp",
    bio: null,
    weiboId: null,
    weiboNickname: null,
    weiboAvatar: null,
    weiboPlatformId: null,
    douyinSecUid: null,
    douyinNickname: null,
    douyinAvatar: null,
    douyinPlatformId: null,
    xhsId: "692c6aac000000000300db53",
    xhsNickname: "云熠小世界",
    xhsAvatar: "/uploads/1780595619236-330245.webp",
    xhsPlatformId: 2,
    igId: null,
    igToken: null,
    igNickname: null,
    igAvatar: null,
    igPlatformId: null,
    syncEnabled: false,
    fullSynced: false,
    createdAt: "2026-06-04T17:54:32.051Z",
    updatedAt: "2026-06-04T17:54:32.051Z",
  },
  {
    id: 2,
    name: "云旗",
    artistId: "yunqi",
    avatar: "/uploads/1780521591404-109038.jpg",
    bio: null,
    weiboId: "7997469042",
    weiboNickname: "云旗Yunqi",
    weiboAvatar: "/uploads/1780569703782-748349.jpg",
    weiboPlatformId: 1,
    douyinSecUid:
      "MS4wLjABAAAA3EZIhf-3zjhy2NwCGYNt2e4gdUl1DXcgRbVRovLUmEeQ1PiFOylXfdPYi1-5T_fz",
    douyinNickname: "云旗Yunqi",
    douyinAvatar: "/uploads/1780569695245-370006.jpg",
    douyinPlatformId: 4,
    xhsId: "63f1f40a000000001001d4a8",
    xhsNickname: "云旗Yunqi",
    xhsAvatar: "/uploads/1780569652610-379374.jpg",
    xhsPlatformId: 2,
    igId: "yunqii_0811",
    igToken: null,
    igNickname: "yunqii_0811",
    igAvatar: "/uploads/1780569672225-582497.jpg",
    igPlatformId: 3,
    syncEnabled: false,
    fullSynced: true,
    createdAt: "2026-06-03T21:19:56.655Z",
    updatedAt: "2026-06-04T17:37:34.253Z",
  },
  {
    id: 1,
    name: "郝熠然",
    artistId: "haoyiran",
    avatar: "/uploads/1780521491823-715722.jpg",
    bio: null,
    weiboId: "6372221076",
    weiboNickname: "郝熠然",
    weiboAvatar: "/uploads/1780570240319-53145.jpg",
    weiboPlatformId: 1,
    douyinSecUid: "MS4wLjABAAAA9hJgduKImx3ZesbSpS3Q3htdTNO5XZXSpiZxIvRXros",
    douyinNickname: "郝熠然",
    douyinAvatar: "/uploads/1780570243862-921643.jpg",
    douyinPlatformId: 4,
    xhsId: "5f6723160000000001006495",
    xhsNickname: "郝熠然",
    xhsAvatar: "/uploads/1780570284938-694924.jpg",
    xhsPlatformId: 2,
    igId: "haoyiran_0912",
    igToken: null,
    igNickname: "haoyiran_0912",
    igAvatar: "/uploads/1780570260413-553192.jpg",
    igPlatformId: 3,
    syncEnabled: false,
    fullSynced: true,
    createdAt: "2026-06-03T21:18:26.931Z",
    updatedAt: "2026-06-04T16:37:51.237Z",
  },
];
